; Converted using ConvPNG
; This file contains all the graphics for easier inclusion in a project
#ifndef gfx_buildings_H
#define gfx_buildings_INC

; assembler defines
#define db .db
#define dw .dw
#define dl .dl

gfx_buildings_transpcolor_index equ 0

#include "gfx/Buildings/barracks.asm" ; 7778 bytes
#include "gfx/Buildings/farm.asm" ; 2114 bytes
#include "gfx/Buildings/house.asm" ; 3330 bytes
#include "gfx/Buildings/lumbercamp.asm" ; 3138 bytes
#include "gfx/Buildings/mill.asm" ; 3330 bytes
#include "gfx/Buildings/miningcamp.asm" ; 2754 bytes
#include "gfx/Buildings/towncenter.asm" ; 12930 bytes

#endif
