#ifndef gfx_main1_H 
#define gfx_main1_INC 
#define db .db 
#define dw .dw 
#define dl .dl 
#include "gfx2/Main/gfx_main1.asm" 
gfx_main1_transpcolor_index equ 0 
#include "gfx2/Main/AoCEI.asm" ; 6889 bytes 
#include "gfx2/Main/soldier.asm" ; 7010 bytes 
#include "gfx2/Main/playhelpquit.asm" ; 2730 bytes 
#include "gfx2/Main/singlemultiplayer.asm" ; 3987 bytes 
#include "gfx2/Main/newloadgame.asm" ; 3342 bytes 
#include "gfx2/Main/intro.asm" ; 9815 bytes 
#endif 
