; Converted using ConvPNG
; This file contains all the graphics for easier inclusion in a project
#ifndef gfx_tiles_H
#define gfx_tiles_INC

; assembler defines
#define db .db
#define dw .dw
#define dl .dl

gfx_tiles_transpcolor_index equ 0

#include "gfx/Tiles/grass.asm" ; 546 bytes
#include "gfx/Tiles/gold.asm" ; 546 bytes
#include "gfx/Tiles/stone.asm" ; 546 bytes
#include "gfx/Tiles/tile_test.asm" ; 546 bytes
#include "gfx/Tiles/tree.asm" ; 2762 bytes

#endif
