; Converted using ConvPNG
; This file contains all the graphics for easier inclusion in a project
#ifndef gfx_main1_H
#define gfx_main1_INC

; assembler defines
#define db .db
#define dw .dw
#define dl .dl

gfx_main1_transpcolor_index equ 0

#include "gfx/Main/AoCEI.asm" ; 5962 bytes
#include "gfx/Main/soldier.asm" ; 7010 bytes
#include "gfx/Main/playhelpquit.asm" ; 3153 bytes
#include "gfx/Main/singlemultiplayer.asm" ; 4725 bytes
#include "gfx/Main/newloadgame.asm" ; 3671 bytes
#include "gfx/Main/intro.asm" ; 9840 bytes

#endif
