; Converted using ConvPNG
; This file contains all the graphics for easier inclusion in a project
#ifndef gfx_buildings_H
#define gfx_buildings_INC

; assembler defines
#define db .db
#define dw .dw
#define dl .dl

#include "gfx2/Buildings/gfx_buildings.asm"
gfx_buildings_transpcolor_index equ 0

#include "gfx2/Buildings/test1.asm" ; 930 bytes
#include "gfx2/Buildings/test2.asm" ; 1026 bytes

#endif
